package eml

import (
	"fmt"
	"strconv"
	"strings"
)

// CodegenOptions control Go source emission.
type CodegenOptions struct {
	PackageName string // Go package name, default "main"
}

// GenerateGo produces a complete Go source file from a parsed .em file.
func GenerateGo(f *File, opts CodegenOptions) (string, error) {
	if opts.PackageName == "" {
		opts.PackageName = "main"
	}
	var b strings.Builder
	b.WriteString("// Code generated by emo 0.1 SDK from " + f.Path + ". DO NOT EDIT.\n\n")
	b.WriteString("package " + opts.PackageName + "\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"github.com/emo-framework/emo/dsl\"\n")
	b.WriteString(")\n\n")

	for _, c := range f.Components {
		emitComponent(&b, f, c)
	}

	if len(f.Components) > 0 {
		first := f.Components[0].Name
		b.WriteString("\n// App is the entry point expected by emo start.\n")
		b.WriteString("func App() dsl.Element { return " + first + "() }\n")
	}

	return b.String(), nil
}

func emitComponent(b *strings.Builder, f *File, c Component) {
	b.WriteString("// " + c.Name + " is generated from " + f.Path + ".\n")
	b.WriteString("func " + c.Name + "() dsl.Element {\n")

	for _, s := range c.States {
		emitStateDecl(b, s)
	}

	if c.Render == nil {
		b.WriteString("\treturn dsl.View()\n")
	} else {
		b.WriteString("\treturn ")
		emitJSXElement(b, f, *c.Render, 1)
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")
}

func emitStateDecl(b *strings.Builder, s StateDecl) {
	helper := "UseState"
	defVal := s.Default.Raw
	switch s.Type {
	case "int":
		helper = "UseStateInt"
	case "string":
		helper = "UseStateString"
	default:
		if _, err := strconv.Atoi(defVal); err == nil {
			helper = "UseStateInt"
		} else if len(defVal) >= 2 && defVal[0] == '"' && defVal[len(defVal)-1] == '"' {
			helper = "UseStateString"
		}
	}
	setter := "set" + capitalize(s.Name)
	b.WriteString("\t" + s.Name + ", " + setter + " := dsl." + helper + "(" + defVal + ")\n")
	b.WriteString("\t_ = " + setter + "\n")
}

// indentStr returns the indentation string for the given depth.
func indentStr(depth int) string {
	return strings.Repeat("\t", depth)
}

func emitJSXElement(b *strings.Builder, f *File, el JSXElement, depth int) {
	indent := indentStr(depth)
	ctor := jsxTagToConstructor(el.Tag)

	// For Text and Button, the first arg is the text content (concatenated
	// from children). For other elements, children are passed via
	// dsl.Children(...).
	if el.Tag == "Text" || el.Tag == "Button" {
		textArg := buildTextArg(el.Children)
		b.WriteString("dsl." + ctor + "(" + textArg)
		// CSS props
		for _, a := range el.Attrs {
			if a.Name == "className" && a.Value.Kind == "string" {
				emitCSSProps(b, f, a.Value.String, depth+1)
			}
		}
		// Explicit attrs (skip className)
		for _, a := range el.Attrs {
			if a.Name == "className" {
				continue
			}
			emitAttr(b, a, depth+1)
		}
		b.WriteString("\n" + indent + ")")
		return
	}

	// Container elements
	b.WriteString("dsl." + ctor + "(\n")

	for _, a := range el.Attrs {
		if a.Name == "className" && a.Value.Kind == "string" {
			emitCSSProps(b, f, a.Value.String, depth+1)
		}
	}

	for _, a := range el.Attrs {
		if a.Name == "className" {
			continue
		}
		emitAttr(b, a, depth+1)
	}

	if len(el.Children) > 0 {
		b.WriteString(indentStr(depth+1) + "dsl.Children(\n")
		for _, c := range el.Children {
			emitChild(b, f, c, depth+2)
		}
		b.WriteString(indentStr(depth+1) + "),\n")
	}

	b.WriteString(indent + ")")
}

// buildTextArg concatenates text and expression children into a single Go
// expression that produces a string. Uses fmt.Sprintf when expressions are
// present, otherwise returns a plain quoted string.
func buildTextArg(children []JSXChild) string {
	if len(children) == 0 {
		return `""`
	}

	// Collect parts: text literals and expressions.
	var parts []string // alternating literal, expr, literal, ...
	var exprs []string
	hasExpr := false

	for _, c := range children {
		switch c.Kind {
		case "text":
			parts = append(parts, c.Text)
		case "expr":
			parts = append(parts, "\x00") // placeholder
			exprs = append(exprs, c.Expr)
			hasExpr = true
		}
	}

	if !hasExpr {
		// Pure text — just quote it.
		if len(parts) == 1 {
			return strconv.Quote(parts[0])
		}
		return strconv.Quote(strings.Join(parts, ""))
	}

	// Has expressions — build a fmt.Sprintf format string.
	var fmtStr strings.Builder
	exprIdx := 0
	for _, p := range parts {
		if p == "\x00" {
			fmtStr.WriteString("%v")
			exprIdx++
		} else {
			fmtStr.WriteString(strings.ReplaceAll(p, "%", "%%"))
		}
	}
	return "fmt.Sprintf(" + strconv.Quote(fmtStr.String()) + ", " + strings.Join(exprs, ", ") + ")"
}

func emitCSSProps(b *strings.Builder, f *File, className string, depth int) {
	if f.CSS == nil {
		return
	}
	props := f.CSS.LookupClass(className)
	if props == nil {
		return
	}
	indent := indentStr(depth)
	for _, k := range sortedKeys(props) {
		v := props[k]
		switch k {
		case "background":
			b.WriteString(indent + "dsl.Bg(" + strconv.Quote(v) + "),\n")
		case "color":
			b.WriteString(indent + "dsl.Fg(" + strconv.Quote(v) + "),\n")
		case "padding":
			b.WriteString(indent + "dsl.Padding(" + formatGoValue(parseCSSDim(v)) + "),\n")
		case "spacing":
			b.WriteString(indent + "dsl.Spacing(" + formatGoValue(parseCSSDim(v)) + "),\n")
		case "font-size":
			b.WriteString(indent + "dsl.Font(" + formatGoValue(parseCSSDim(v)) + ", \"normal\"),\n")
		case "font-weight":
			b.WriteString(indent + "dsl.Prop(\"fontWeight\", " + strconv.Quote(v) + "),\n")
		case "width":
			b.WriteString(indent + "dsl.Width(" + formatGoValue(parseCSSDimOrKeyword(v)) + "),\n")
		case "height":
			b.WriteString(indent + "dsl.Height(" + formatGoValue(parseCSSDimOrKeyword(v)) + "),\n")
		default:
			b.WriteString(indent + "dsl.Prop(" + strconv.Quote(k) + ", " + strconv.Quote(v) + "),\n")
		}
	}
}

func emitAttr(b *strings.Builder, a JSXAttr, depth int) {
	indent := indentStr(depth)
	switch a.Name {
	case "onClick":
		body := rewriteStateAssign(a.Value.Expr)
		b.WriteString(indent + "dsl.OnClick(func() { " + body + " }),\n")
	case "onChange":
		body := rewriteStateAssign(a.Value.Expr)
		param := extractOnChangeParam(a.Value.Expr)
		if param == "" {
			param = "_v"
		}
		b.WriteString(indent + "dsl.OnChange(func(" + param + " string) { " + body + " }),\n")
	case "spacing":
		b.WriteString(indent + "dsl.Spacing(" + numVal(a.Value) + "),\n")
	case "padding":
		b.WriteString(indent + "dsl.Padding(" + numVal(a.Value) + "),\n")
	case "background":
		b.WriteString(indent + "dsl.Bg(" + strVal(a.Value) + "),\n")
	case "color":
		b.WriteString(indent + "dsl.Fg(" + strVal(a.Value) + "),\n")
	case "fontSize":
		b.WriteString(indent + "dsl.Font(" + numVal(a.Value) + ", \"normal\"),\n")
	case "fontWeight":
		b.WriteString(indent + "dsl.Prop(\"fontWeight\", " + strVal(a.Value) + "),\n")
	default:
		b.WriteString(indent + "dsl.Prop(" + strconv.Quote(a.Name) + ", " + formatAttrValue(a.Value) + "),\n")
	}
}

// numVal returns the numeric value from a JSXAttrValue, handling both number
// and expression kinds.
func numVal(v JSXAttrValue) string {
	if v.Kind == "number" {
		return v.Number
	}
	if v.Kind == "expr" {
		return v.Expr
	}
	return "0"
}

// strVal returns the string value from a JSXAttrValue, quoting if necessary.
func strVal(v JSXAttrValue) string {
	if v.Kind == "string" {
		return strconv.Quote(v.String)
	}
	if v.Kind == "expr" {
		return v.Expr
	}
	return `""`
}

func emitChild(b *strings.Builder, f *File, c JSXChild, depth int) {
	indent := indentStr(depth)
	switch c.Kind {
	case "text":
		b.WriteString(indent + "dsl.Text(" + strconv.Quote(c.Text) + "),\n")
	case "expr":
		b.WriteString(indent + "dsl.Text(fmt.Sprintf(\"%v\", " + c.Expr + ")),\n")
	case "element":
		b.WriteString(indent)
		emitJSXElement(b, f, *c.Element, depth)
		b.WriteString(",\n")
	}
}

func jsxTagToConstructor(tag string) string {
	switch tag {
	case "Scaffold", "Column", "Row", "View", "Text", "Button", "TextField", "Image", "Spacer", "Divider":
		return tag
	default:
		return tag
	}
}

// rewriteStateAssign converts expressions like "count = count + 1" to
// "setCount(count + 1)".
func rewriteStateAssign(expr string) string {
	expr = strings.TrimSpace(expr)
	if i := strings.Index(expr, "=>"); i >= 0 {
		lhs := strings.TrimSpace(expr[:i])
		if lhs == "()" || lhs == "(_)" {
			return rewriteStateAssign(strings.TrimSpace(expr[i+2:]))
		}
	}
	if strings.HasPrefix(expr, "(") {
		cparen := strings.IndexByte(expr, ')')
		if cparen > 0 && strings.HasPrefix(expr[cparen:], ") =>") {
			param := strings.TrimSpace(expr[1:cparen])
			body := strings.TrimSpace(expr[cparen+4:])
			return rewriteAssign(body, param)
		}
	}
	return rewriteAssign(expr, "")
}

func rewriteAssign(body, onChangeParam string) string {
	body = strings.TrimSpace(body)
	eq := strings.IndexByte(body, '=')
	if eq < 0 {
		return body
	}
	lhs := strings.TrimSpace(body[:eq])
	rhs := strings.TrimSpace(body[eq+1:])
	if strings.HasPrefix(rhs, "=") {
		return body
	}
	if onChangeParam != "" && lhs == onChangeParam {
		return body
	}
	return "set" + capitalize(lhs) + "(" + rhs + ")"
}

func extractOnChangeParam(expr string) string {
	expr = strings.TrimSpace(expr)
	if strings.HasPrefix(expr, "(") {
		c := strings.IndexByte(expr, ')')
		if c > 0 {
			return strings.TrimSpace(expr[1:c])
		}
	}
	if i := strings.Index(expr, "=>"); i > 0 {
		return strings.TrimSpace(expr[:i])
	}
	return ""
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func formatGoValue(v any) string {
	switch x := v.(type) {
	case string:
		return strconv.Quote(x)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	case int:
		return strconv.Itoa(x)
	default:
		return fmt.Sprintf("%v", v)
	}
}

func formatAttrValue(v JSXAttrValue) string {
	switch v.Kind {
	case "string":
		return strconv.Quote(v.String)
	case "number":
		return v.Number
	case "expr":
		return v.Expr
	}
	return "nil"
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && keys[j-1] > keys[j]; j-- {
			keys[j-1], keys[j] = keys[j], keys[j-1]
		}
	}
	return keys
}
