// Package syncer keeps the per-project android/ folder in sync with .em and
// .css file changes. On every file save, the syncer regenerates native Kotlin
// source code that mirrors the emo components, so the android/ project always
// has up-to-date native code that can be compiled into a standalone APK.
//
// The syncer writes two files:
//
//   android/app/src/main/java/dev/emo/app/GeneratedComponents.kt
//     — Kotlin @Composable functions for each .em component
//
//   android/app/src/main/res/values/emo_styles.xml
//     — Android XML resources for CSS styles (colors, dimensions)
package syncer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/emo-framework/emo/codegen"
	"github.com/emo-framework/emo/dsl"
	"github.com/emo-framework/emo/eml"
)

// Syncer watches .em/.css changes and regenerates native Kotlin + XML in the
// project's android/ folder.
type Syncer struct {
	projectDir  string
	packageName string
}

// New creates a Syncer for the given project directory.
func New(projectDir, packageName string) *Syncer {
	if packageName == "" {
		packageName = "dev.emo.app"
	}
	return &Syncer{
		projectDir:  projectDir,
		packageName: packageName,
	}
}

// SyncAll regenerates all native code from the project's .em files.
func (s *Syncer) SyncAll() error {
	emFiles, err := findAllEMFiles(s.projectDir)
	if err != nil {
		return err
	}
	if len(emFiles) == 0 {
		return nil
	}

	var allComponents []eml.Component
	var cssRules []eml.CSSRule
	for _, emFile := range emFiles {
		f, err := eml.TranspileFile(emFile)
		if err != nil {
			continue
		}
		allComponents = append(allComponents, f.Components...)
		if f.CSS != nil {
			cssRules = append(cssRules, f.CSS.Rules...)
		}
	}

	kotlin := s.generateKotlin(allComponents)
	kotlinPath := s.kotlinPath()
	if err := os.MkdirAll(filepath.Dir(kotlinPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(kotlinPath, []byte(kotlin), 0o644); err != nil {
		return fmt.Errorf("write kotlin: %w", err)
	}

	xml := s.generateXML(cssRules)
	xmlPath := s.xmlPath()
	if err := os.MkdirAll(filepath.Dir(xmlPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(xmlPath, []byte(xml), 0o644); err != nil {
		return fmt.Errorf("write xml: %w", err)
	}

	return nil
}

func (s *Syncer) kotlinPath() string {
	pkgDir := strings.ReplaceAll(s.packageName, ".", "/")
	return filepath.Join(s.projectDir, "android", "app", "src", "main", "java", pkgDir, "GeneratedComponents.kt")
}

func (s *Syncer) xmlPath() string {
	return filepath.Join(s.projectDir, "android", "app", "src", "main", "res", "values", "emo_styles.xml")
}

func (s *Syncer) generateKotlin(components []eml.Component) string {
	var b strings.Builder
	b.WriteString("// AUTO-GENERATED by emo syncer. DO NOT EDIT.\n")
	b.WriteString("// Regenerated on every .em/.css file change.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", s.packageName))
	b.WriteString("import androidx.compose.foundation.layout.*\n")
	b.WriteString("import androidx.compose.foundation.rememberScrollState\n")
	b.WriteString("import androidx.compose.foundation.verticalScroll\n")
	b.WriteString("import androidx.compose.material3.*\n")
	b.WriteString("import androidx.compose.runtime.*\n")
	b.WriteString("import androidx.compose.ui.Alignment\n")
	b.WriteString("import androidx.compose.ui.Modifier\n")
	b.WriteString("import androidx.compose.ui.graphics.Color\n")
	b.WriteString("import androidx.compose.ui.text.font.FontWeight\n")
	b.WriteString("import androidx.compose.ui.unit.dp\n")
	b.WriteString("import androidx.compose.ui.unit.sp\n")
	b.WriteString("import androidx.compose.ui.viewinterop.AndroidView\n\n")

	if len(components) > 0 {
		first := components[0].Name
		b.WriteString(fmt.Sprintf("// EmoRoot — entry point, renders %s.\n@Composable\nfun EmoRoot() {\n    %s()\n}\n\n", first, first))
	}

	for _, c := range components {
		s.emitComponent(&b, c)
	}
	return b.String()
}

func (s *Syncer) emitComponent(b *strings.Builder, c eml.Component) {
	b.WriteString(fmt.Sprintf("// %s — generated from .em.\n@Composable\nfun %s() {\n", c.Name, c.Name))
	for _, st := range c.States {
		dv := st.Default.Raw
		if isIntLit(dv) {
			b.WriteString(fmt.Sprintf("    var %s by remember { mutableIntStateOf(%s) }\n", st.Name, dv))
		} else if isStringLit(dv) {
			b.WriteString(fmt.Sprintf("    var %s by remember { mutableStateOf(%s) }\n", st.Name, dv))
		} else if dv == "true" || dv == "false" {
			b.WriteString(fmt.Sprintf("    var %s by remember { mutableStateOf(%s) }\n", st.Name, dv))
		} else {
			b.WriteString(fmt.Sprintf("    var %s by remember { mutableStateOf(%s) }\n", st.Name, dv))
		}
	}
	if c.Render != nil {
		b.WriteString("    ")
		s.emitJSX(b, *c.Render, 1)
	} else {
		b.WriteString("    Box() {}\n")
	}
	b.WriteString("}\n\n")
}

func (s *Syncer) emitJSX(b *strings.Builder, el eml.JSXElement, depth int) {
	indent := strings.Repeat("    ", depth)
	switch el.Tag {
	case "Column":
		b.WriteString("Column(modifier = Modifier.fillMaxWidth()")
		for _, a := range el.Attrs {
			if a.Name == "padding" && a.Value.Kind == "number" {
				b.WriteString(fmt.Sprintf(".padding(%s.dp)", a.Value.Number))
			}
		}
		b.WriteString(", verticalArrangement = Arrangement.spacedBy(")
		sp := "0.dp"
		for _, a := range el.Attrs {
			if a.Name == "spacing" && a.Value.Kind == "number" {
				sp = a.Value.Number + ".dp"
			}
		}
		b.WriteString(sp + ")) {\n")
		s.emitChildren(b, el.Children, depth+1)
		b.WriteString(indent + "}\n")
	case "Row":
		b.WriteString("Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {\n")
		s.emitChildren(b, el.Children, depth+1)
		b.WriteString(indent + "}\n")
	case "Text":
		text := s.buildText(el.Children)
		b.WriteString(fmt.Sprintf("Text(%q", text))
		for _, a := range el.Attrs {
			if a.Name == "fontSize" && a.Value.Kind == "number" {
				b.WriteString(fmt.Sprintf(", fontSize = %s.sp", a.Value.Number))
			}
			if a.Name == "fontWeight" && a.Value.String == "bold" {
				b.WriteString(", fontWeight = FontWeight.Bold")
			}
		}
		b.WriteString(")\n")
	case "Button":
		text := s.buildText(el.Children)
		onClick := s.extractOnClick(el)
		if onClick == "" {
			onClick = "{}"
		}
		b.WriteString(fmt.Sprintf("Button(onClick = { %s }) { Text(%q) }\n", onClick, text))
	case "Input", "TextField":
		ph := s.getAttr(el, "placeholder")
		b.WriteString(fmt.Sprintf("var _t by remember { mutableStateOf(\"\") }\n%sTextField(value = _t, onValueChange = { _t = it }, placeholder = { Text(%q) })\n", indent, ph))
	case "WebView":
		src := s.getAttr(el, "source")
		b.WriteString(fmt.Sprintf("AndroidView(factory = { ctx -> android.webkit.WebView(ctx).apply { settings.javaScriptEnabled = true; loadUrl(%q) } }, modifier = Modifier.fillMaxWidth().height(300.dp))\n", src))
	case "Switch":
		b.WriteString("Switch(checked = false, onCheckedChange = {})\n")
	case "Slider":
		b.WriteString("Slider(value = 0.5f, onValueChange = {})\n")
	case "Divider":
		b.WriteString("HorizontalDivider()\n")
	case "Spacer":
		b.WriteString("Spacer(Modifier.height(8.dp))\n")
	case "Card":
		b.WriteString("Card(Modifier.fillMaxWidth().padding(8.dp)) { Column(Modifier.padding(16.dp)) {\n")
		s.emitChildren(b, el.Children, depth+2)
		b.WriteString(indent + "}}\n")
	case "SafeAreaView":
		b.WriteString("Column(Modifier.fillMaxSize()) {\n")
		s.emitChildren(b, el.Children, depth+1)
		b.WriteString(indent + "}\n")
	case "ScrollView":
		b.WriteString("Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState())) {\n")
		s.emitChildren(b, el.Children, depth+1)
		b.WriteString(indent + "}\n")
	case "TopBar":
		title := s.getAttr(el, "title")
		b.WriteString(fmt.Sprintf("Text(%q, fontSize = 20.sp, fontWeight = FontWeight.Bold, modifier = Modifier.fillMaxWidth().padding(16.dp))\n", title))
	case "ActivityIndicator":
		b.WriteString("Box(Modifier.fillMaxWidth().padding(16.dp), contentAlignment = Alignment.Center) { CircularProgressIndicator() }\n")
	case "Progress":
		b.WriteString("LinearProgressIndicator(Modifier.fillMaxWidth().padding(16.dp))\n")
	case "Fab":
		b.WriteString("FloatingActionButton(onClick = {}) { Text(\"+\") }\n")
	default:
		b.WriteString(fmt.Sprintf("%s()\n", el.Tag))
	}
}

func (s *Syncer) emitChildren(b *strings.Builder, children []eml.JSXChild, depth int) {
	indent := strings.Repeat("    ", depth)
	for _, c := range children {
		switch c.Kind {
		case "text":
			b.WriteString(fmt.Sprintf("%sText(%q)\n", indent, c.Text))
		case "expr":
			b.WriteString(fmt.Sprintf("%sText(\"${%s}\")\n", indent, c.Expr))
		case "element":
			b.WriteString(indent)
			s.emitJSX(b, *c.Element, depth)
		}
	}
}

func (s *Syncer) buildText(children []eml.JSXChild) string {
	var result string
	for _, c := range children {
		if c.Kind == "text" {
			result += c.Text
		}
	}
	return result
}

func (s *Syncer) getAttr(el eml.JSXElement, name string) string {
	for _, a := range el.Attrs {
		if a.Name == name {
			switch a.Value.Kind {
			case "string":
				return a.Value.String
			case "expr":
				return "${" + a.Value.Expr + "}"
			case "number":
				return a.Value.Number
			}
		}
	}
	return ""
}

func (s *Syncer) extractOnClick(el eml.JSXElement) string {
	for _, a := range el.Attrs {
		if a.Name == "onClick" && a.Value.Kind == "expr" {
			return rewriteStateAssignKotlin(a.Value.Expr)
		}
	}
	return ""
}

func rewriteStateAssignKotlin(expr string) string {
	expr = strings.TrimSpace(expr)
	if i := strings.Index(expr, "=>"); i >= 0 {
		lhs := strings.TrimSpace(expr[:i])
		if lhs == "()" || lhs == "(_)" {
			return rewriteStateAssignKotlin(strings.TrimSpace(expr[i+2:]))
		}
	}
	return expr
}

func (s *Syncer) generateXML(rules []eml.CSSRule) string {
	var b strings.Builder
	b.WriteString("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
	b.WriteString("<!-- AUTO-GENERATED by emo syncer. CSS → Android resources. -->\n<resources>\n")
	colors := make(map[string]string)
	dimens := make(map[string]string)
	for _, rule := range rules {
		className := strings.TrimPrefix(rule.Selector, ".")
		for prop, val := range rule.Props {
			resName := className + "_" + strings.ReplaceAll(prop, "-", "_")
			switch prop {
			case "background", "color":
				if strings.HasPrefix(val, "#") {
					colors[resName] = val
				}
			case "padding", "spacing", "font-size", "width", "height":
				num := strings.TrimSuffix(strings.TrimSuffix(strings.TrimSuffix(val, "dp"), "sp"), "px")
				dimens[resName] = num
			}
		}
	}
	if len(colors) > 0 {
		b.WriteString("\n    <!-- CSS colors -->\n")
		for name, val := range colors {
			b.WriteString(fmt.Sprintf("    <color name=\"%s\">%s</color>\n", name, val))
		}
	}
	if len(dimens) > 0 {
		b.WriteString("\n    <!-- CSS dimensions (dp) -->\n")
		for name, val := range dimens {
			b.WriteString(fmt.Sprintf("    <dimen name=\"%s\">%sdp</dimen>\n", name, val))
		}
	}
	b.WriteString("</resources>\n")
	return b.String()
}

func findAllEMFiles(root string) ([]string, error) {
	var files []string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			name := info.Name()
			if name == "android" || name == "build" || name == ".emo" ||
				name == "__emo_gen__" || name == "node_modules" || name == ".git" {
				return filepath.SkipDir
			}
			return nil
		}
		if filepath.Ext(path) == ".em" {
			files = append(files, path)
		}
		return nil
	})
	return files, err
}

func isIntLit(s string) bool {
	s = strings.TrimSpace(s)
	if s == "" {
		return false
	}
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}

func isStringLit(s string) bool {
	s = strings.TrimSpace(s)
	return len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"'
}

// SyncAndLog runs SyncAll and logs the result.
func (s *Syncer) SyncAndLog() {
	if err := s.SyncAll(); err != nil {
		fmt.Printf("[sync] error: %v\n", err)
	} else {
		fmt.Printf("[sync] android/ native code updated ✓\n")
	}
}

// RenderTreeToKotlin converts a dsl.Element tree to standalone Kotlin code.
func RenderTreeToKotlin(tree dsl.Element, packageName string) string {
	return codegen.Build(tree, codegen.Options{
		PackageName: packageName,
		ClassName:   "EmoRoot",
		Standalone:  true,
	})
}
