// Package codegen translates an emo vtree (dsl.Element) into runnable Kotlin
// Jetpack Compose source.
//
// Two modes are supported:
//
//   1. Full codegen (`Build`) — emit a complete MainActivity.kt for `emo build`.
//      This produces a standalone APK that ships without the dev server.
//
//   2. Hot-swap patch (`Diff`) — given an old and new vtree, produce a list of
//      mutations the emo Go preview app can apply without restarting the
//      activity. The preview app receives these patches and mutates its live
//      Compose state in place.
//
// The codegen is intentionally straightforward: each element kind maps to a
// well-known Compose composable. Props map to modifier calls or composable
// parameters. Children are inlined as trailing lambda content.
package codegen

import (
	"fmt"
	"strings"

	"github.com/emo-framework/emo/dsl"
)

// Options controls codegen behaviour.
type Options struct {
	PackageName string // Kotlin package, default "dev.emo.generated"
	ClassName   string // Top-level composable name, default "EmoRoot"
	Standalone  bool   // true: emit a full Activity; false: emit only the composable
}

// Build produces a complete Kotlin source file from a vtree.
func Build(root dsl.Element, opts Options) string {
	if opts.PackageName == "" {
		opts.PackageName = "dev.emo.generated"
	}
	if opts.ClassName == "" {
		opts.ClassName = "EmoRoot"
	}

	var b strings.Builder
	b.WriteString("// AUTO-GENERATED by emo codegen. DO NOT EDIT.\n")
	b.WriteString("// Source: emo Go vtree → Jetpack Compose.\n\n")
	b.WriteString("package " + opts.PackageName + "\n\n")
	b.WriteString("import androidx.compose.foundation.layout.*\n")
	b.WriteString("import androidx.compose.foundation.*\n")
	b.WriteString("import androidx.compose.material3.*\n")
	b.WriteString("import androidx.compose.runtime.*\n")
	b.WriteString("import androidx.compose.ui.*\n")
	b.WriteString("import androidx.compose.ui.graphics.Color\n")
	b.WriteString("import androidx.compose.ui.text.font.FontWeight\n")
	b.WriteString("import androidx.compose.ui.unit.dp\n")
	b.WriteString("import androidx.compose.ui.unit.sp\n")
	b.WriteString("import androidx.compose.material.icons.*\n\n")

	if opts.Standalone {
		b.WriteString(standaloneActivity(opts.ClassName))
		b.WriteString("\n")
	}

	b.WriteString("@Composable\n")
	b.WriteString("fun " + opts.ClassName + "() {\n")
	emitElement(&b, root, 1)
	b.WriteString("}\n")
	return b.String()
}

// emitElement writes the Kotlin composable invocation for one element and
// recurses into its children.
func emitElement(b *strings.Builder, e dsl.Element, depth int) {
	indent := strings.Repeat("    ", depth)

	switch e.Kind {
	case dsl.KindScaffold:
		b.WriteString(indent + "Scaffold(\n")
		emitModifiers(b, e, depth+1)
		b.WriteString(indent + ") {\n")
		b.WriteString(indent + "    Column(Modifier.padding(16.dp)) {\n")
		for _, c := range e.Children {
			emitElement(b, c, depth+2)
		}
		b.WriteString(indent + "    }\n")
		b.WriteString(indent + "}\n")

	case dsl.KindColumn:
		b.WriteString(indent + "Column(\n")
		emitModifiers(b, e, depth+1)
		b.WriteString(indent + ") {\n")
		for _, c := range e.Children {
			emitElement(b, c, depth+1)
		}
		b.WriteString(indent + "}\n")

	case dsl.KindRow:
		b.WriteString(indent + "Row(\n")
		emitModifiers(b, e, depth+1)
		b.WriteString(indent + ") {\n")
		for _, c := range e.Children {
			emitElement(b, c, depth+1)
		}
		b.WriteString(indent + "}\n")

	case dsl.KindView:
		b.WriteString(indent + "Box(\n")
		emitModifiers(b, e, depth+1)
		b.WriteString(indent + ") {\n")
		for _, c := range e.Children {
			emitElement(b, c, depth+1)
		}
		b.WriteString(indent + "}\n")

	case dsl.KindText:
		b.WriteString(indent + "Text(\n")
		b.WriteString(indent + fmt.Sprintf("    text = %q,\n", e.Text))
		emitModifiers(b, e, depth+1)
		b.WriteString(indent + ")\n")

	case dsl.KindButton:
		b.WriteString(indent + "Button(\n")
		b.WriteString(indent + fmt.Sprintf("    onClick = { emoClick(%q) },\n", handlerToken(e, "click")))
		emitModifiers(b, e, depth+1)
		b.WriteString(indent + ") {\n")
		b.WriteString(indent + fmt.Sprintf("    Text(%q)\n", e.Text))
		b.WriteString(indent + "}\n")

	case dsl.KindTextField:
		placeholder := strProp(e, "placeholder")
		b.WriteString(indent + "var _text by remember { mutableStateOf(\"\") }\n")
		b.WriteString(indent + "TextField(\n")
		b.WriteString(indent + fmt.Sprintf("    value = _text,\n"))
		b.WriteString(indent + fmt.Sprintf("    onValueChange = { v -> _text = v; emoChange(%q, v) },\n", handlerToken(e, "change")))
		b.WriteString(indent + fmt.Sprintf("    placeholder = { Text(%q) },\n", placeholder))
		emitModifiers(b, e, depth+1)
		b.WriteString(indent + ")\n")

	case dsl.KindImage:
		src := strProp(e, "source")
		b.WriteString(indent + "Image(\n")
		b.WriteString(indent + fmt.Sprintf("    painter = rememberAsyncImagePainter(%q),\n", src))
		emitModifiers(b, e, depth+1)
		b.WriteString(indent + ")\n")

	case dsl.KindSpacer:
		b.WriteString(indent + "Spacer(Modifier")
		if w := e.Props["weight"]; w != nil {
			b.WriteString(fmt.Sprintf(".weight(%v)", w))
		}
		b.WriteString(")\n")

	case dsl.KindDivider:
		b.WriteString(indent + "Divider()\n")

	default:
		b.WriteString(indent + fmt.Sprintf("// unknown element kind: %s\n", e.Kind))
	}
}

// emitModifiers walks the element's props and emits a Modifier chain.
func emitModifiers(b *strings.Builder, e dsl.Element, depth int) {
	indent := strings.Repeat("    ", depth)
	mod := "Modifier"

	if v, ok := e.Props["padding"]; ok {
		mod += fmt.Sprintf(".padding(%v.dp)", v)
	}
	if v, ok := e.Props["margin"]; ok {
		// Compose has no margin; emulate with outer padding wrapper would be
		// needed. For now we ignore margin in codegen.
		_ = v
	}
	if v, ok := e.Props["background"]; ok {
		mod += fmt.Sprintf(".background(Color(%q))", v)
	}
	if v, ok := e.Props["width"]; ok {
		mod += emitDimension(".width", v)
	}
	if v, ok := e.Props["height"]; ok {
		mod += emitDimension(".height", v)
	}
	if v, ok := e.Props["spacing"]; ok {
		// Column/Row spacing goes as a constructor arg, not a modifier.
		b.WriteString(indent + fmt.Sprintf("verticalArrangement = Arrangement.spacedBy(%v.dp),\n", v))
	}
	if e.Kind == dsl.KindRow {
		if v, ok := e.Props["spacing"]; ok {
			b.WriteString(indent + fmt.Sprintf("horizontalArrangement = Arrangement.spacedBy(%v.dp),\n", v))
		}
	}
	if v, ok := e.Props["color"]; ok {
		// Color prop on Text → textColor arg.
		b.WriteString(indent + fmt.Sprintf("color = Color(%q),\n", v))
	}
	if v, ok := e.Props["fontSize"]; ok {
		b.WriteString(indent + fmt.Sprintf("fontSize = %v.sp,\n", v))
	}
	if v, ok := e.Props["fontWeight"]; ok {
		w := "FontWeight.Normal"
		if s, ok := v.(string); ok && s == "bold" {
			w = "FontWeight.Bold"
		}
		b.WriteString(indent + fmt.Sprintf("fontWeight = %s,\n", w))
	}

	b.WriteString(indent + "modifier = " + mod + "\n")
}

func emitDimension(name string, v any) string {
	switch x := v.(type) {
	case float64:
		return fmt.Sprintf("%s(%v.dp)", name, x)
	case int:
		return fmt.Sprintf("%s(%d.dp)", name, x)
	case string:
		switch x {
		case "match":
			return fmt.Sprintf("%s(0.dp).fillMaxWidth()", name)
		case "wrap":
			return fmt.Sprintf("%s(IntrinsicSize.Min)", name)
		default:
			return fmt.Sprintf("%s(%v.dp)", name, x)
		}
	}
	return ""
}

// handlerToken returns the opaque token for the named event on the element, or
// empty string if not attached.
func handlerToken(e dsl.Element, event string) string {
	for _, h := range e.Handlers {
		if h.Event == event {
			return h.Token
		}
	}
	return ""
}

func strProp(e dsl.Element, key string) string {
	if v, ok := e.Props[key]; ok {
		if s, ok := v.(string); ok {
			return s
		}
	}
	return ""
}

// standaloneActivity emits a MainActivity that hosts the emo root composable
// for `emo build` standalone APKs.
func standaloneActivity(rootName string) string {
	return fmt.Sprintf(`class MainActivity : android.app.Activity() {
    override fun onCreate(savedInstanceState: android.os.Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                %[1]s()
            }
        }
    }
}
`, rootName)
}
